/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'titleHindi' : string,
  'body' : string,
  'createdAt' : Time,
  'targetBranch' : string,
  'bodyHindi' : string,
}
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'checkIn' : [] | [Time],
  'date' : string,
  'checkOut' : [] | [Time],
}
export type AttendanceStatus = { 'onLeave' : null } |
  { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface Branch { 'id' : bigint, 'name' : string }
export interface DigitalIdCard {
  'rejectedReason' : [] | [string],
  'approvedAt' : Time,
  'isActive' : boolean,
  'employeeId' : Principal,
  'validUntil' : Time,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'branch' : string,
  'nameHindi' : string,
  'name' : string,
  'rank' : bigint,
  'points' : bigint,
}
export interface LeaveBalance {
  'emergency' : bigint,
  'sick' : bigint,
  'earned' : bigint,
  'casual' : bigint,
}
export interface RegistrationRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'branch' : string,
  'requester' : Principal,
  'nameHindi' : string,
  'rejectedReason' : [] | [string],
  'name' : string,
  'role' : Role,
  'employeeId' : string,
  'phone' : string,
  'department' : string,
}
export type Role = { 'supervisor' : null } |
  { 'employee' : null } |
  { 'management' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'descriptionHindi' : string,
  'title' : string,
  'branch' : string,
  'completionNote' : [] | [string],
  'assignedTo' : Principal,
  'titleHindi' : string,
  'dueDate' : Time,
  'description' : string,
  'approvalReason' : [] | [string],
  'approved' : [] | [boolean],
  'priority' : TaskPriority,
}
export type TaskPriority = { 'routine' : null } |
  { 'urgent' : null };
export type TaskStatus = { 'pending' : null } |
  { 'blocked' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'branch' : string,
  'nameHindi' : string,
  'name' : string,
  'role' : Role,
  'isActive' : boolean,
  'employeeId' : string,
  'phone' : string,
  'department' : string,
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBranch' : ActorMethod<[string], bigint>,
  'approveDigitalIdRequest' : ActorMethod<
    [Principal, boolean, [] | [string]],
    undefined
  >,
  'approveRegistrationRequest' : ActorMethod<[Principal], [] | [UserProfile]>,
  'approveTask' : ActorMethod<[bigint, boolean, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[], undefined>,
  'checkOut' : ActorMethod<[], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createTask' : ActorMethod<
    [string, string, string, string, Principal, Time, TaskPriority, string],
    bigint
  >,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  'deleteBranch' : ActorMethod<[bigint], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllDigitalIds' : ActorMethod<[], Array<DigitalIdCard>>,
  'getAssignedTasks' : ActorMethod<[], Array<Task>>,
  'getAttendanceHistory' : ActorMethod<[Principal], Array<AttendanceRecord>>,
  'getBranchAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLeaveBalance' : ActorMethod<[], LeaveBalance>,
  /**
   * / Gets the leave balance for a given principal.
   */
  'getLeaveBalanceForPrincipal' : ActorMethod<[Principal], LeaveBalance>,
  'getMyDigitalId' : ActorMethod<[], [] | [DigitalIdCard]>,
  'getMyRegistrationStatus' : ActorMethod<[], [] | [RegistrationRequest]>,
  /**
   * / Gets the next available announcement ID.
   */
  'getNextAnnouncementId' : ActorMethod<[], bigint>,
  /**
   * / Gets the next available task ID.
   */
  'getNextTaskId' : ActorMethod<[], bigint>,
  'getOwnPointsAndRank' : ActorMethod<
    [],
    { 'rank' : bigint, 'points' : bigint }
  >,
  'getPendingDigitalIdRequests' : ActorMethod<[], Array<Principal>>,
  'getPendingRegistrationRequests' : ActorMethod<
    [],
    Array<RegistrationRequest>
  >,
  /**
   * / Gets the points reward for a given task priority.
   */
  'getPointsRewardForTask' : ActorMethod<[TaskPriority], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAnnouncementAsRead' : ActorMethod<[bigint], undefined>,
  'rejectRegistrationRequest' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDigitalIdRequest' : ActorMethod<[], undefined>,
  'submitRegistrationRequest' : ActorMethod<
    [string, string, Role, string, string, string, string],
    undefined
  >,
  'updateBranch' : ActorMethod<[bigint, string], undefined>,
  'updateLeaveBalance' : ActorMethod<
    [Principal, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updatePoints' : ActorMethod<[Principal, bigint], undefined>,
  'updateTaskStatus' : ActorMethod<
    [bigint, TaskStatus, [] | [string]],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];