/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({
  'supervisor' : IDL.Null,
  'employee' : IDL.Null,
  'management' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'branch' : IDL.Text,
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'isActive' : IDL.Bool,
  'employeeId' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'points' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskPriority = IDL.Variant({
  'routine' : IDL.Null,
  'urgent' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'titleHindi' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'targetBranch' : IDL.Text,
  'bodyHindi' : IDL.Text,
});
export const DigitalIdCard = IDL.Record({
  'rejectedReason' : IDL.Opt(IDL.Text),
  'approvedAt' : Time,
  'isActive' : IDL.Bool,
  'employeeId' : IDL.Principal,
  'validUntil' : Time,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'blocked' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'descriptionHindi' : IDL.Text,
  'title' : IDL.Text,
  'branch' : IDL.Text,
  'completionNote' : IDL.Opt(IDL.Text),
  'assignedTo' : IDL.Principal,
  'titleHindi' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
  'approvalReason' : IDL.Opt(IDL.Text),
  'approved' : IDL.Opt(IDL.Bool),
  'priority' : TaskPriority,
});
export const AttendanceStatus = IDL.Variant({
  'onLeave' : IDL.Null,
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'checkIn' : IDL.Opt(Time),
  'date' : IDL.Text,
  'checkOut' : IDL.Opt(Time),
});
export const Branch = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'branch' : IDL.Text,
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'points' : IDL.Nat,
});
export const LeaveBalance = IDL.Record({
  'emergency' : IDL.Nat,
  'sick' : IDL.Nat,
  'earned' : IDL.Nat,
  'casual' : IDL.Nat,
});
export const RegistrationRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'branch' : IDL.Text,
  'requester' : IDL.Principal,
  'nameHindi' : IDL.Text,
  'rejectedReason' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : Role,
  'employeeId' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBranch' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'approveDigitalIdRequest' : IDL.Func(
      [IDL.Principal, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'approveRegistrationRequest' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      [],
    ),
  'approveTask' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([], [], []),
  'checkOut' : IDL.Func([], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        Time,
        TaskPriority,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createUserProfile' : IDL.Func([UserProfile], [], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllDigitalIds' : IDL.Func([], [IDL.Vec(DigitalIdCard)], ['query']),
  'getAssignedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAttendanceHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getBranchAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLeaveBalance' : IDL.Func([], [LeaveBalance], ['query']),
  'getLeaveBalanceForPrincipal' : IDL.Func(
      [IDL.Principal],
      [LeaveBalance],
      ['query'],
    ),
  'getMyDigitalId' : IDL.Func([], [IDL.Opt(DigitalIdCard)], ['query']),
  'getMyRegistrationStatus' : IDL.Func(
      [],
      [IDL.Opt(RegistrationRequest)],
      ['query'],
    ),
  'getNextAnnouncementId' : IDL.Func([], [IDL.Nat], ['query']),
  'getNextTaskId' : IDL.Func([], [IDL.Nat], ['query']),
  'getOwnPointsAndRank' : IDL.Func(
      [],
      [IDL.Record({ 'rank' : IDL.Nat, 'points' : IDL.Nat })],
      ['query'],
    ),
  'getPendingDigitalIdRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPendingRegistrationRequests' : IDL.Func(
      [],
      [IDL.Vec(RegistrationRequest)],
      ['query'],
    ),
  'getPointsRewardForTask' : IDL.Func([TaskPriority], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAnnouncementAsRead' : IDL.Func([IDL.Nat], [], []),
  'rejectRegistrationRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDigitalIdRequest' : IDL.Func([], [], []),
  'submitRegistrationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, Role, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBranch' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateLeaveBalance' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updatePoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateTaskStatus' : IDL.Func(
      [IDL.Nat, TaskStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({
    'supervisor' : IDL.Null,
    'employee' : IDL.Null,
    'management' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'branch' : IDL.Text,
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'isActive' : IDL.Bool,
    'employeeId' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'points' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskPriority = IDL.Variant({
    'routine' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'titleHindi' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'targetBranch' : IDL.Text,
    'bodyHindi' : IDL.Text,
  });
  const DigitalIdCard = IDL.Record({
    'rejectedReason' : IDL.Opt(IDL.Text),
    'approvedAt' : Time,
    'isActive' : IDL.Bool,
    'employeeId' : IDL.Principal,
    'validUntil' : Time,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'blocked' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'descriptionHindi' : IDL.Text,
    'title' : IDL.Text,
    'branch' : IDL.Text,
    'completionNote' : IDL.Opt(IDL.Text),
    'assignedTo' : IDL.Principal,
    'titleHindi' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
    'approvalReason' : IDL.Opt(IDL.Text),
    'approved' : IDL.Opt(IDL.Bool),
    'priority' : TaskPriority,
  });
  const AttendanceStatus = IDL.Variant({
    'onLeave' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'checkIn' : IDL.Opt(Time),
    'date' : IDL.Text,
    'checkOut' : IDL.Opt(Time),
  });
  const Branch = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'branch' : IDL.Text,
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const LeaveBalance = IDL.Record({
    'emergency' : IDL.Nat,
    'sick' : IDL.Nat,
    'earned' : IDL.Nat,
    'casual' : IDL.Nat,
  });
  const RegistrationRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'branch' : IDL.Text,
    'requester' : IDL.Principal,
    'nameHindi' : IDL.Text,
    'rejectedReason' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : Role,
    'employeeId' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBranch' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'approveDigitalIdRequest' : IDL.Func(
        [IDL.Principal, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'approveRegistrationRequest' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        [],
      ),
    'approveTask' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([], [], []),
    'checkOut' : IDL.Func([], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          Time,
          TaskPriority,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createUserProfile' : IDL.Func([UserProfile], [], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllDigitalIds' : IDL.Func([], [IDL.Vec(DigitalIdCard)], ['query']),
    'getAssignedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAttendanceHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getBranchAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLeaveBalance' : IDL.Func([], [LeaveBalance], ['query']),
    'getLeaveBalanceForPrincipal' : IDL.Func(
        [IDL.Principal],
        [LeaveBalance],
        ['query'],
      ),
    'getMyDigitalId' : IDL.Func([], [IDL.Opt(DigitalIdCard)], ['query']),
    'getMyRegistrationStatus' : IDL.Func(
        [],
        [IDL.Opt(RegistrationRequest)],
        ['query'],
      ),
    'getNextAnnouncementId' : IDL.Func([], [IDL.Nat], ['query']),
    'getNextTaskId' : IDL.Func([], [IDL.Nat], ['query']),
    'getOwnPointsAndRank' : IDL.Func(
        [],
        [IDL.Record({ 'rank' : IDL.Nat, 'points' : IDL.Nat })],
        ['query'],
      ),
    'getPendingDigitalIdRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPendingRegistrationRequests' : IDL.Func(
        [],
        [IDL.Vec(RegistrationRequest)],
        ['query'],
      ),
    'getPointsRewardForTask' : IDL.Func([TaskPriority], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAnnouncementAsRead' : IDL.Func([IDL.Nat], [], []),
    'rejectRegistrationRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDigitalIdRequest' : IDL.Func([], [], []),
    'submitRegistrationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, Role, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBranch' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateLeaveBalance' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updatePoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateTaskStatus' : IDL.Func(
        [IDL.Nat, TaskStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };