/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    principal: Principal;
    branch: string;
    nameHindi: string;
    name: string;
    rank: bigint;
    points: bigint;
}
export type Time = bigint;
export interface FileCategory {
    id: bigint;
    name: string;
    createdBy: Principal;
    allowedRoles: Array<Role>;
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    descriptionHindi: string;
    title: string;
    branch: string;
    completionNote?: string;
    assignedTo: Principal;
    titleHindi: string;
    dueDate: Time;
    description: string;
    approvalReason?: string;
    approved?: boolean;
    priority: TaskPriority;
}
export interface Branch {
    id: bigint;
    name: string;
}
export interface FileRecord {
    id: bigint;
    categoryId: bigint;
    fileData: Uint8Array;
    fileName: string;
    fileType: string;
    uploadedAt: Time;
    uploadedBy: Principal;
}
export interface RegistrationRequest {
    status: Variant_pending_approved_rejected;
    branch: string;
    requester: Principal;
    nameHindi: string;
    rejectedReason?: string;
    name: string;
    role: Role;
    employeeId: string;
    phone: string;
    department: string;
}
export interface AttendanceRecord {
    status: AttendanceStatus;
    checkIn?: Time;
    date: string;
    checkOut?: Time;
}
export interface Announcement {
    id: bigint;
    title: string;
    titleHindi: string;
    body: string;
    createdAt: Time;
    targetBranch: string;
    bodyHindi: string;
}
export interface LeaveBalance {
    emergency: bigint;
    sick: bigint;
    earned: bigint;
    casual: bigint;
}
export interface UserProfile {
    id: Principal;
    branch: string;
    nameHindi: string;
    name: string;
    role: Role;
    isActive: boolean;
    employeeId: string;
    phone: string;
    department: string;
    points: bigint;
}
export interface DigitalIdCard {
    rejectedReason?: string;
    approvedAt: Time;
    isActive: boolean;
    employeeId: Principal;
    validUntil: Time;
}
export enum AttendanceStatus {
    onLeave = "onLeave",
    present = "present",
    late = "late",
    absent = "absent"
}
export enum Role {
    supervisor = "supervisor",
    employee = "employee",
    management = "management"
}
export enum TaskPriority {
    routine = "routine",
    urgent = "urgent"
}
export enum TaskStatus {
    pending = "pending",
    blocked = "blocked",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBranch(name: string): Promise<bigint>;
    approveDigitalIdRequest(employeeId: Principal, approved: boolean, reason: string | null): Promise<void>;
    approveRegistrationRequest(requester: Principal): Promise<UserProfile | null>;
    approveTask(taskId: bigint, approved: boolean, reason: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkIn(): Promise<void>;
    checkOut(): Promise<void>;
    createAnnouncement(title: string, titleHindi: string, body: string, bodyHindi: string, targetBranch: string): Promise<bigint>;
    createFileCategory(name: string, allowedRoles: Array<Role>): Promise<bigint>;
    createTask(title: string, titleHindi: string, description: string, descriptionHindi: string, assignedTo: Principal, dueDate: Time, priority: TaskPriority, branch: string): Promise<bigint>;
    createUserProfile(profile: UserProfile): Promise<void>;
    deactivateUser(userId: Principal): Promise<void>;
    deleteBranch(id: bigint): Promise<void>;
    deleteFile(fileId: bigint): Promise<void>;
    deleteFileCategory(id: bigint): Promise<void>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllDigitalIds(): Promise<Array<DigitalIdCard>>;
    getAllFiles(): Promise<Array<FileRecord>>;
    getAssignedTasks(): Promise<Array<Task>>;
    getAttendanceHistory(userId: Principal): Promise<Array<AttendanceRecord>>;
    getBranchAttendance(branch: string): Promise<Array<AttendanceRecord>>;
    getBranches(): Promise<Array<Branch>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFileCategories(): Promise<Array<FileCategory>>;
    getFilesForCategory(categoryId: bigint): Promise<Array<FileRecord>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getLeaveBalance(): Promise<LeaveBalance>;
    /**
     * / Gets the leave balance for a given principal.
     */
    getLeaveBalanceForPrincipal(employeeId: Principal): Promise<LeaveBalance>;
    getMyDigitalId(): Promise<DigitalIdCard | null>;
    getMyRegistrationStatus(): Promise<RegistrationRequest | null>;
    /**
     * / Gets the next available announcement ID.
     */
    getNextAnnouncementId(): Promise<bigint>;
    /**
     * / Gets the next available task ID.
     */
    getNextTaskId(): Promise<bigint>;
    getOwnPointsAndRank(): Promise<{
        rank: bigint;
        points: bigint;
    }>;
    getPendingDigitalIdRequests(): Promise<Array<Principal>>;
    getPendingRegistrationRequests(): Promise<Array<RegistrationRequest>>;
    /**
     * / Gets the points reward for a given task priority.
     */
    getPointsRewardForTask(priority: TaskPriority): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAnnouncementAsRead(announcementId: bigint): Promise<void>;
    rejectRegistrationRequest(requester: Principal, reason: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitDigitalIdRequest(): Promise<void>;
    submitRegistrationRequest(name: string, nameHindi: string, role: Role, department: string, branch: string, phone: string, employeeId: string): Promise<void>;
    updateBranch(id: bigint, name: string): Promise<void>;
    updateFileCategory(id: bigint, name: string, allowedRoles: Array<Role>): Promise<void>;
    updateLeaveBalance(employeeId: Principal, sick: bigint, casual: bigint, earned: bigint, emergency: bigint): Promise<void>;
    updatePoints(userId: Principal, points: bigint): Promise<void>;
    updateTaskStatus(taskId: bigint, status: TaskStatus, completionNote: string | null): Promise<void>;
    updateUserProfile(userId: Principal, profile: UserProfile): Promise<void>;
    uploadFile(categoryId: bigint, fileName: string, fileType: string, fileData: Uint8Array): Promise<bigint>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, DigitalIdCard as _DigitalIdCard, FileCategory as _FileCategory, RegistrationRequest as _RegistrationRequest, Role as _Role, Task as _Task, TaskPriority as _TaskPriority, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBranch(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBranch(arg0);
            return result;
        }
    }
    async approveDigitalIdRequest(arg0: Principal, arg1: boolean, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDigitalIdRequest(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDigitalIdRequest(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async approveRegistrationRequest(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRegistrationRequest(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRegistrationRequest(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveTask(arg0: bigint, arg1: boolean, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTask(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTask(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIn(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn();
            return result;
        }
    }
    async checkOut(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut();
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createFileCategory(arg0: string, arg1: Array<Role>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFileCategory(arg0, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFileCategory(arg0, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Principal, arg5: Time, arg6: TaskPriority, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_TaskPriority_n12(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_TaskPriority_n12(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async createUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteBranch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteFile(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteFileCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileCategory(arg0);
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getAllDigitalIds(): Promise<Array<DigitalIdCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDigitalIds();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDigitalIds();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFiles(): Promise<Array<FileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFiles();
            return result;
        }
    }
    async getAssignedTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedTasks();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedTasks();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceHistory(arg0: Principal): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceHistory(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceHistory(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBranchAttendance(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranchAttendance(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranchAttendance(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranches();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileCategories(): Promise<Array<FileCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileCategories();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileCategories();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilesForCategory(arg0: bigint): Promise<Array<FileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilesForCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilesForCategory(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLeaveBalance(): Promise<LeaveBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveBalance();
            return result;
        }
    }
    async getLeaveBalanceForPrincipal(arg0: Principal): Promise<LeaveBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveBalanceForPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveBalanceForPrincipal(arg0);
            return result;
        }
    }
    async getMyDigitalId(): Promise<DigitalIdCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDigitalId();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDigitalId();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRegistrationStatus(): Promise<RegistrationRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRegistrationStatus();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRegistrationStatus();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextAnnouncementId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextAnnouncementId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextAnnouncementId();
            return result;
        }
    }
    async getNextTaskId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextTaskId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextTaskId();
            return result;
        }
    }
    async getOwnPointsAndRank(): Promise<{
        rank: bigint;
        points: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnPointsAndRank();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnPointsAndRank();
            return result;
        }
    }
    async getPendingDigitalIdRequests(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDigitalIdRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDigitalIdRequests();
            return result;
        }
    }
    async getPendingRegistrationRequests(): Promise<Array<RegistrationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRegistrationRequests();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRegistrationRequests();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPointsRewardForTask(arg0: TaskPriority): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointsRewardForTask(to_candid_TaskPriority_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointsRewardForTask(to_candid_TaskPriority_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAnnouncementAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAnnouncementAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAnnouncementAsRead(arg0);
            return result;
        }
    }
    async rejectRegistrationRequest(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRegistrationRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRegistrationRequest(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDigitalIdRequest(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDigitalIdRequest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDigitalIdRequest();
            return result;
        }
    }
    async submitRegistrationRequest(arg0: string, arg1: string, arg2: Role, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistrationRequest(arg0, arg1, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistrationRequest(arg0, arg1, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateBranch(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0, arg1);
            return result;
        }
    }
    async updateFileCategory(arg0: bigint, arg1: string, arg2: Array<Role>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFileCategory(arg0, arg1, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFileCategory(arg0, arg1, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateLeaveBalance(arg0: Principal, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveBalance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveBalance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePoints(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePoints(arg0, arg1);
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n46(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n46(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateUserProfile(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadFile(arg0: bigint, arg1: string, arg2: string, arg3: Uint8Array): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DigitalIdCard_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DigitalIdCard): DigitalIdCard {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FileCategory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileCategory): FileCategory {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationRequest_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationRequest): RegistrationRequest {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DigitalIdCard]): DigitalIdCard | null {
    return value.length === 0 ? null : from_candid_DigitalIdCard_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RegistrationRequest]): RegistrationRequest | null {
    return value.length === 0 ? null : from_candid_RegistrationRequest_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rejectedReason: [] | [string];
    approvedAt: _Time;
    isActive: boolean;
    employeeId: Principal;
    validUntil: _Time;
}): {
    rejectedReason?: string;
    approvedAt: Time;
    isActive: boolean;
    employeeId: Principal;
    validUntil: Time;
} {
    return {
        rejectedReason: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.rejectedReason)),
        approvedAt: value.approvedAt,
        isActive: value.isActive,
        employeeId: value.employeeId,
        validUntil: value.validUntil
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    descriptionHindi: string;
    title: string;
    branch: string;
    completionNote: [] | [string];
    assignedTo: Principal;
    titleHindi: string;
    dueDate: _Time;
    description: string;
    approvalReason: [] | [string];
    approved: [] | [boolean];
    priority: _TaskPriority;
}): {
    id: bigint;
    status: TaskStatus;
    descriptionHindi: string;
    title: string;
    branch: string;
    completionNote?: string;
    assignedTo: Principal;
    titleHindi: string;
    dueDate: Time;
    description: string;
    approvalReason?: string;
    approved?: boolean;
    priority: TaskPriority;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n23(_uploadFile, _downloadFile, value.status),
        descriptionHindi: value.descriptionHindi,
        title: value.title,
        branch: value.branch,
        completionNote: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.completionNote)),
        assignedTo: value.assignedTo,
        titleHindi: value.titleHindi,
        dueDate: value.dueDate,
        description: value.description,
        approvalReason: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.approvalReason)),
        approved: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.approved)),
        priority: from_candid_TaskPriority_n26(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AttendanceStatus;
    checkIn: [] | [_Time];
    date: string;
    checkOut: [] | [_Time];
}): {
    status: AttendanceStatus;
    checkIn?: Time;
    date: string;
    checkOut?: Time;
} {
    return {
        status: from_candid_AttendanceStatus_n31(_uploadFile, _downloadFile, value.status),
        checkIn: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.checkIn)),
        date: value.date,
        checkOut: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.checkOut))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdBy: Principal;
    allowedRoles: Array<_Role>;
}): {
    id: bigint;
    name: string;
    createdBy: Principal;
    allowedRoles: Array<Role>;
} {
    return {
        id: value.id,
        name: value.name,
        createdBy: value.createdBy,
        allowedRoles: from_candid_vec_n39(_uploadFile, _downloadFile, value.allowedRoles)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    branch: string;
    nameHindi: string;
    name: string;
    role: _Role;
    isActive: boolean;
    employeeId: string;
    phone: string;
    department: string;
    points: bigint;
}): {
    id: Principal;
    branch: string;
    nameHindi: string;
    name: string;
    role: Role;
    isActive: boolean;
    employeeId: string;
    phone: string;
    department: string;
    points: bigint;
} {
    return {
        id: value.id,
        branch: value.branch,
        nameHindi: value.nameHindi,
        name: value.name,
        role: from_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        employeeId: value.employeeId,
        phone: value.phone,
        department: value.department,
        points: value.points
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    branch: string;
    requester: Principal;
    nameHindi: string;
    rejectedReason: [] | [string];
    name: string;
    role: _Role;
    employeeId: string;
    phone: string;
    department: string;
}): {
    status: Variant_pending_approved_rejected;
    branch: string;
    requester: Principal;
    nameHindi: string;
    rejectedReason?: string;
    name: string;
    role: Role;
    employeeId: string;
    phone: string;
    department: string;
} {
    return {
        status: from_candid_variant_n44(_uploadFile, _downloadFile, value.status),
        branch: value.branch,
        requester: value.requester,
        nameHindi: value.nameHindi,
        rejectedReason: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.rejectedReason)),
        name: value.name,
        role: from_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        employeeId: value.employeeId,
        phone: value.phone,
        department: value.department
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    blocked: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "blocked" in value ? TaskStatus.blocked : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    routine: null;
} | {
    urgent: null;
}): TaskPriority {
    return "routine" in value ? TaskPriority.routine : "urgent" in value ? TaskPriority.urgent : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onLeave: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "onLeave" in value ? AttendanceStatus.onLeave : "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supervisor: null;
} | {
    employee: null;
} | {
    management: null;
}): Role {
    return "supervisor" in value ? Role.supervisor : "employee" in value ? Role.employee : "management" in value ? Role.management : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DigitalIdCard>): Array<DigitalIdCard> {
    return value.map((x)=>from_candid_DigitalIdCard_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileCategory>): Array<FileCategory> {
    return value.map((x)=>from_candid_FileCategory_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Role>): Array<Role> {
    return value.map((x)=>from_candid_Role_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegistrationRequest>): Array<RegistrationRequest> {
    return value.map((x)=>from_candid_RegistrationRequest_n42(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    branch: string;
    nameHindi: string;
    name: string;
    role: Role;
    isActive: boolean;
    employeeId: string;
    phone: string;
    department: string;
    points: bigint;
}): {
    id: Principal;
    branch: string;
    nameHindi: string;
    name: string;
    role: _Role;
    isActive: boolean;
    employeeId: string;
    phone: string;
    department: string;
    points: bigint;
} {
    return {
        id: value.id,
        branch: value.branch,
        nameHindi: value.nameHindi,
        name: value.name,
        role: to_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        employeeId: value.employeeId,
        phone: value.phone,
        department: value.department,
        points: value.points
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    supervisor: null;
} | {
    employee: null;
} | {
    management: null;
} {
    return value == Role.supervisor ? {
        supervisor: null
    } : value == Role.employee ? {
        employee: null
    } : value == Role.management ? {
        management: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    routine: null;
} | {
    urgent: null;
} {
    return value == TaskPriority.routine ? {
        routine: null
    } : value == TaskPriority.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    blocked: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.blocked ? {
        blocked: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Role>): Array<_Role> {
    return value.map((x)=>to_candid_Role_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
